version: '3.8'

services:
    postgresdb:
        image: postgres:latest
        hostname: postgresdb
        ports:
            - "15432:5432"
        restart: always
        environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        volumes:
        - ./init:/docker-entrypoint-initdb.d
        - postgresVolume:/var/lib/postgres
        - postgresConfig:/etc/postgres/
        env_file: ./.env
        networks:
            cm-compose-network:
                aliases:
                    - postgresdb

    critical-monitor:
        build:
            context: .
        ports:
        - 3000:5000
        environment:
        - SECRET_KEY=${SECRET_KEY}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_HOST=postgresdb
        - POSTGRES_PORT=${POSTGRES_PORT}
        env_file: ./.env
        depends_on:
            - postgresdb
        networks:
            - cm-compose-network
volumes:
    postgresVolume:
    postgresConfig:

networks: 
    cm-compose-network:
        driver: bridge