"""empty message

Revision ID: 047bdbfcd8dc
Revises: 05dc0a849478
Create Date: 2021-10-23 09:06:57.949901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047bdbfcd8dc'
down_revision = '05dc0a849478'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('width_og', sa.Integer(), nullable=True))
    op.add_column('config', sa.Column('height_og', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'height_og')
    op.drop_column('config', 'width_og')
    # ### end Alembic commands ###
