"""empty message

Revision ID: 068b7e7188aa
Revises: 0180c04f29e3
Create Date: 2021-12-01 20:50:27.035673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068b7e7188aa'
down_revision = '0180c04f29e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('size_frame', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'size_frame')
    # ### end Alembic commands ###
