"""empty message

Revision ID: 0f41f5bc73c8
Revises: 068b7e7188aa
Create Date: 2021-12-13 15:09:52.030312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f41f5bc73c8'
down_revision = '068b7e7188aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_user_username'), 'telegram_user', ['username'], unique=True)
    op.create_table('users_alert',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'config_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_alert')
    op.drop_index(op.f('ix_telegram_user_username'), table_name='telegram_user')
    op.drop_table('telegram_user')
    # ### end Alembic commands ###
