"""empty message

Revision ID: 26d3b9e6e87f
Revises: 047bdbfcd8dc
Create Date: 2021-10-28 19:32:34.841367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26d3b9e6e87f'
down_revision = '047bdbfcd8dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('capacity', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'capacity')
    # ### end Alembic commands ###
