"""empty message

Revision ID: a6e92cc50a6a
Revises: 26d3b9e6e87f
Create Date: 2021-11-02 07:51:49.623959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6e92cc50a6a'
down_revision = '26d3b9e6e87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurrence_type', sa.String(length=15), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('amount_of_people', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['config.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('occurrence')
    # ### end Alembic commands ###
